### ISSUE TITLE
Merge firmware repositories, use Docker image for build?

### ISSUE THREAD

**Issue by charliebruce** [OpenSource-EBike-firmware/ebike_wireless_remote#48]
It's come up a few times in discussion, most recently in #47 - at the moment the project seems to be split across multiple repos, and each has a copy of the nRF5 SDK, possibly with some modifications applied. This structure ends up being a pain to work with - the repo is quite large as a result of the SDK, submodules aren't very user-friendly, and CI builds are fragile.

I've had good success on multiple projects using Nordic chips, by setting up as follows:

* App, bootloader and manufacturing test app all exist in a single repo.
* Each of the above sub-projects is built by a main Makefile. The main Makefile then generates the DFU package and merged hex file.
* Building takes place within a [Docker environment](https://github.com/charliebruce/nrf5-docker-build), containing the nRF5 SDK, GCC toolchain and a few helpers (eg `srec_cat`). I've built one of these images for each revision of the nRF5 SDK. 
* The root Makefile overrides the relevant environment variables, so you should be able to use the stock Nordic Makefiles for each sub-project. The only thing I think you need to add is to override the default hardware version ID in the Bootloader (defaults to `52` for all products otherwise)
* Github Actions builds each commit for each hardware revision which exists. Each hardware revision runs in a separate job, and uploads the artefacts. 
* When building locally, each hardware revision is built into a different build directory, avoiding the need for a clean rebuild when changing pinout for example. You'd run `make PCBVER=2` to change PCB/wiring version, which would automatically build into a new build directory. This should make it easier in future if custom PCBs are being made / there end up being different hardware or schematics in use.

I've released an example project [here](https://github.com/charliebruce/nrf5-example-project) which demonstrates all this functionality. It should pretty much be possible to drop the app into a new directory called `app`, bootloader into one called `boot`, set up the correct SDK version in `products.mk`, and call `make` in the root directory. 

One possible sticking point - at one point Docker required Windows Pro for good performance, and Docker's generally a bit heavy. Might discourage some contributions from people with lower-end machines. Not sure if this is still an issue.

I don't have the time or a full understanding of how the team likes to work, so I didn't want to jump in and majorly restructure these repos and possibly break people's existing flows, but I would be happy to do so if everyone's happy with this (may take a little while to get around to this). Alternatively, happy to give any help/advice/review if someone else wants to take this on instead.

Would welcome any thoughts/discussion on this!

**Comment by casainho** [comment]
I appreciate the help.

The main reason to make this new change was because of the need to reuse some code between all projects. Right now I do not feel the need to anything more, so, why take more time learning new tools instead of developing the project?

I develop on a small 9 inches, low power, laptop GPD P2 MAX, so I want to avoid docker - I had some small experience professionally and I could understand it was very slow on this small and low power laptop, so I want to avoid use it.
