### ISSUE TITLE
error when building code

### ISSUE THREAD

**Issue by simonperneel** [OpenSource-EBike-firmware/ebike_wireless_remote#49]
Hi, thanks for sharing this interesting project!

I followed the documentation for code development. However, when I try to compile the firmware code with gcc, i get the following error:

**fatal error:** ant_key_manager_config.h: No such file or directory

Do I need to set additional dependencies or what is the problem?

Cheers, Simon

**Comment by casainho** [comment]
DEPRECATED.
Use this one instead: https://github.com/OpenSourceEBike/TSDZ2_wireless
