### ISSUE TITLE
Makefile:291: Cannot find include folder: ./nRF5_SDK_16.0.0/components/ant/ant_key_manager/config

### ISSUE THREAD

**Issue by stsdc** [OpenSource-EBike-firmware/ebike_wireless_remote#9]
Did I miss something when was making CI? Or is it just current state?

**Comment by casainho** [comment]
Let´s see if @rananna can see this issue.

**Comment by stsdc** [comment]
Looks like You approved code too early? 😅️

**Comment by rananna** [comment]
this file is intentionally left out of the build as we are not allowed to distribute the Garmin provided ANT+ network keys to developers that have not registered on their website.
If you want to compile the code you need to register.
Situation described here:
https://www.thisisant.com/developer/resources/tech-bulletin/network-keys-and-the-ant-managed-network
since we are non commetcial we should be ok to use the key, but we still cannot distribute freely on github.

**Comment by rananna** [comment]
@casainho, the compile problem because of the missing ANT+ network  keys needs to be fixed.
I propose to add an explanation to developers in the Readme that they need to get the key from Garmin. I will add a dummy key file to the firmware to eliminate the compile problem along with an explanation  to add the Garmin keys to this file so that Ant works.
Does this sound good to you?

**Comment by casainho** [comment]
@rananna yes, please do that!!

Maybe you can also add warnings so the developers will see them while building the firmware, like:

#warning DUMMY ANT NETWORK KEY USED!! YOU NEED TO REGISTER, etc, etc
#warning https://www.thisisant.com/developer/resources/tech-bulletin/network-keys-and-the-ant-managed-network

**Comment by rananna** [comment]
Good idea I will do that

**Comment by casainho** [comment]
Maybe you do not need to add explanation on the readme but add short explanation on that warnings, a developers should understand a short explanation. Better to avoid duplication of information.

**Comment by rananna** [comment]
Yes, I will add ro only the code . Better idea than readme mod.

**Comment by rananna** [comment]
Do you know if you can force GCC to throw a user defined warning when compiling ?

**Comment by casainho** [comment]
Yes, it is:

#warning text

#error text

error should stop the compilation which is not what we want because we want the build tests to pass.

**Comment by rananna** [comment]
Perfect! Just what I need. Thanks!

**Comment by stsdc** [comment]
This might be useful: [Encrypted secrets](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets).  It is better not to store any secret keys in the repo.
Also I have a questions. Please correct me if I'm wrong.
1. The only purpose of ANT+ is to connect this remote with *TSDZ Wireless* (and other devices that support this protocol)?
2. So every person that wants to use this firmware-hardware stack should acquire a key?
3. But is it possible to use *TSDZ Wireless* without remote? Only a mobile app?

**Comment by rananna** [comment]
ANT+ is needed by the remote to communicate with the TSDZ2 (and any other ebike supporting ANT+ LEV) as well as the Garmin edge bike computers.
Every developer that wants to link this ANT + stack will need to acquire the developer key from Garmin.
I will let @casainho answer the question on the use of the wireless controller  without the remote.

**Comment by stsdc** [comment]
What I'm thinking is that we might still distribute the binaries, just without ANT+ support. So only an android app will be working.

Also, I don't know how it is working right now, but would be cool to just paste the developer key into an app. And the app will send it to *remote* and *TSDZ wireless*. So there will be no need to hardcode the key.

**Comment by casainho** [comment]
If we want to buy the licenses then we would need to do it both for ANT and Bluetooth. As this is not a commercial project, I think there is not issue with that. I think the shops that are now selling TSDZ2 with our firmware installed, will need to pay the licenses before selling the product.

We will need to put this information clear on the project page.

**Comment by stsdc** [comment]
OK. So, if You will build binary with Your key, is it OK to make this binary publicly available?

**Comment by casainho** [comment]
Yes. The ANT key is the same for everyone, I already found it on a github of some project.

**Comment by stsdc** [comment]
OK. So, are we going to put it just in the repo, or in [encrypted secrets](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets)?

**Comment by casainho** [comment]
I don´t know. I am busy developing the firmware connection to / and Android app. That encrypted secrets is new to me, it is not my priority right now.

Maybe you can help with it?

**Comment by stsdc** [comment]
It requires collaborators/admin access to repository. I don't know if You want to give it to a random person 😅️

I'm just concerned about the distribution of binaries by CI, but if firmware<->Android app will work without the key it is not urgent.

**Comment by casainho** [comment]
OK, I see. If the releases are manual, then I will build with the key when making the release HEX files.

If the secrets required admin to repository, if you write some sequence list of steps, I can do it.

**Comment by stsdc** [comment]
The point is to make releases automatic. I may try write a script that will inject a secret into a code.

**Comment by stsdc** [comment]
We have this error again.

**Comment by rananna** [comment]
I think this happens when @Casainho does a PR merge.
I have the file in .gitignore on my computer, so it is not uploaded to github in my repository.
Not enough of a GitHub expert to know how to fix this so it doesn't delete the demo file in the main repo.

**Comment by stsdc** [comment]
To build on CI we should use secrets. We should prepare simple txt file with this key. In `Makefile` we should check if this file is not empty and inject the key into the code. If key file is empty, it means we are running `make` in CI, so key will be taken from env variable.

Only admin/collaborator can do this, so I'm not doing any PRs, because I have no access.
